openapi: 3.0.3
info:
  version: 1.0.0
  title: Monki Projects API
servers:
  - description: Monki Projects' API v1 (production)
    url: 'https://api.monkiprojects.com'
  - description: Monki Projects' API v1 (staging / development)
    url: 'https://staging.api.monkiprojects.com'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
