openapi: 3.0.3
info:
  version: 1.0.0
  title: Monki Projects API
servers:
  - url: 'https://{environment}.monkiprojects.com'
    description: Monki Projects API v1
    variables:
      environment:
        default: api     # Production server
        enum:
          - api          # Production server
          - pre-prod.api # Development server
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
