inputs:
  - inputFile: ./base.yaml
  - inputFile: ./specs/users-api-v1.yaml
    disputePrefix: Users
  - inputFile: ./specs/placemarks-api-v1.yaml
    disputePrefix: Placemarks
output: ./specs/monki-projects-api-v1.yaml
