inputs:
  - inputFile: ./base.yaml
  - inputFile: ./users-api-v1.yaml
    disputePrefix: Users
  - inputFile: ./placemarks-api-v1.yaml
    disputePrefix: Placemarks
output: ./monki-projects-api-v1.yaml
