openapi: 3.0.3
info:
  version: 1.0.0
  title: Monki Projects' Auth API
servers:
  - url: 'https://{environment}.monkiprojects.com/auth/v1'
    description: Monki Projects' Auth API v1
    variables:
      environment:
        default: api     # Production server
        enum:
          - api          # Production server
          - pre-prod.api # Development server
tags:
  - name: auth
    description: Endpoints related to authentication.
paths:
  '/login':
    post:
      summary: Log In
      operationId: logIn
      tags: [auth]
      security:
        - BasicAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BearerToken'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    # ===== Auth =====
    BearerToken:
      description: A Bearer token.
      type: string
  responses:
    UnauthorizedError:
      description: Authentication information is missing or is invalid.
      content:
        application/json:
          schema:
            $ref: 'schemas.yaml#/Error'